### ISSUE TITLE
Migrate away from jcenter

### ISSUE THREAD

**Issue by salberin** [al-broco/android-http-digest#2]
Hi, 

As JCenter will be closing its doors before the end of may 2021, can I please request that this artifact is moved to mavenCentral?

Many thanks in advance

**Comment by al-broco** [comment]
Thanks for the heads up! I'll move ASAP.

**Comment by al-broco** [comment]
Artifacts now available from Maven Central: https://search.maven.org/artifact/com.albroco/bare-bones-digest/1.0.2/aar
